# Site settings
name: The Abbeywood Irregulars
email: contact@abbeywoodirregulars.uk

description: > # this means to ignore newlines until "baseurl:"
  The Abbeywood Irregulars are a mixed bag of wargamers who meet monthly for larger games (typically up to 16 players) and to put on games at wargames shows.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abbeywoodirregulars.uk" # the base hostname & protocol for your site

header: yes
header_sm: images/awi-banner-small.jpg
header_med: images/awi-banner-med.jpg
header_large: images/awi-banner-large.jpg
header_xl: images/awi-banner-xl.jpg


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, .last_optimized]


# Build settings
markdown: rdiscount
